root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["vendor", "tmp", ".git"]
  include_ext = ["go", "html", "tpl"]

[log]
  time = false

[watcher]
  poll = true  # Required for Docker volume changes
  poll_interval = 500