
services:
  nats:
    image: nats:latest
    container_name: nats
    restart: always
    ports:
      - "${NATS_CLIENT_PORT}:${NATS_CLIENT_PORT}"
      - "${NATS_MONITOR_PORT}:${NATS_MONITOR_PORT}"
      - "${NATS_WEBSOCKET_PORT}:${NATS_WEBSOCKET_PORT}"
    volumes:
      - ./config/nats.conf:/container/nats.conf
    command: "-c /container/nats.conf"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
