x-env: &environment-variables
  env_file:
    - ./.env
  environment:
    APP_PORT: "${APP_PORT}"
    APP_METRICS_PORT: "${APP_METRICS_PORT}"
    APP_ENV: "${APP_ENV}"
    APP_CLIENT_URL: "${APP_CLIENT_URL}"
    APP_CLIENT_NAME: "${APP_CLIENT_NAME}"
    APP_TOKEN: "${APP_TOKEN}"
    APP_NAME: "${APP_NAME}"
    NATS_HOST: "${NATS_HOST}"
    NATS_CLIENT_PORT: "${NATS_CLIENT_PORT}"
    NATS_MONITOR_PORT: "${NATS_MONITOR_PORT}"
    NATS_WEBSOCKET_PORT: "${NATS_WEBSOCKET_PORT}"
    DATABASE_URL: "${DATABASE_URL}"
    DB_MAX_IDLE_CONN: "${DB_MAX_IDLE_CONN}"
    DB_MAX_OPEN_CONN: "${DB_MAX_OPEN_CONN}"
    DB_MAX_LIFETIME: "${DB_MAX_LIFETIME}"
    REDIS_PORT: "${REDIS_PORT}"
    REDIS_HOST: "${REDIS_HOST}"
    REDIS_PASSWORD: "${REDIS_PASSWORD}"
    REDIS_USERNAME: "${REDIS_USERNAME}"
    SMTP_HOST: "${SMTP_HOST}"
    SMTP_PORT: "${SMTP_PORT}"
    SMTP_USERNAME: "${SMTP_USERNAME}"
    SMTP_PASSWORD: "${SMTP_PASSWORD}"
    SMTP_FROM: "${SMTP_FROM}"
    SMTP_TEST_RECIEVER: "${SMTP_TEST_RECIEVER}"
    TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
    TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
    TWILIO_SENDER: "${TWILIO_SENDER}"
    TWILIO_TEST_RECIEVER: "${TWILIO_TEST_RECIEVER}"
    STORAGE_ACCESS_KEY: "${STORAGE_ACCESS_KEY}"
    STORAGE_SECRET_KEY: "${STORAGE_SECRET_KEY}"
    STORAGE_BUCKET: "${STORAGE_BUCKET}"
    STORAGE_PREFIX: "${STORAGE_PREFIX}"
    STORAGE_MAX_SIZE: "${STORAGE_MAX_SIZE}"
    PASSWORD_MEMORY: "${PASSWORD_MEMORY}"
    PASSWORD_ITERATIONS: "${PASSWORD_ITERATIONS}"
    PASSWORD_PARALLELISM: "${PASSWORD_PARALLELISM}"
    PASSWORD_SALT_LENTH: "${PASSWORD_SALT_LENTH}"
    PASSWORD_KEY_LENGTH: "${PASSWORD_KEY_LENGTH}"
    PASSWORD_SECRET: "${PASSWORD_SECRET}"
    OTP_SECRET: "${OTP_SECRET}"
    QR_SECRET: "${QR_SECRET}"

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_METRICS_PORT}:${APP_METRICS_PORT}"
    volumes:
      - ./:/app
    <<: *environment-variables
   