

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":${STORAGE_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: "${STORAGE_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${STORAGE_SECRET_KEY}"
    env_file:
      - ./.env
    ports:
      - "${STORAGE_API_PORT}:9000"
      - "${STORAGE_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    env_file:
      - ./.env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - app-network
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    env_file:
      - ./.env
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-network
    
  redisinsight:  
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    environment: 
      REDISINSIGHT_PORT: "${REDISINSIGHT_PORT}"
    env_file:
      - ./.env
    ports:
      - "${REDISINSIGHT_PORT}:${REDISINSIGHT_PORT}"
    depends_on:
      - redis
    networks:
      - app-network
  
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    environment:
      MAILPIT_SMTP_PORT: "${MAILPIT_SMTP_PORT}"
      MAILPIT_UI_PORT: "${MAILPIT_UI_PORT}"
    env_file:
      - ./.env
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_UI_PORT:-8025}:8025"
    networks:
      - app-network
  
  nats:
    image: nats:latest
    container_name: nats
    restart: always
    environment:
      NATS_MONITOR_PORT: "${NATS_MONITOR_PORT}"
      NATS_CLIENT_PORT: "${NATS_CLIENT_PORT}"
    env_file:
      - ./.env
    ports:
      - "${NATS_CLIENT_PORT}:${NATS_CLIENT_PORT}"
      - "${NATS_MONITOR_PORT}:${NATS_MONITOR_PORT}"
      - "8080:8080"
    volumes:
      - ./config/nats.conf:/container/nats.conf
    command: "-c /container/nats.conf"
    networks:
      - app-network
  
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    restart: always
    environment:
      SCYLLA_CLUSTER_NAME: "${SCYLLA_CLUSTER_NAME:-scylla-cluster}"
      SCYLLA_KEYSPACE: "${SCYLLA_KEYSPACE:-mykeyspace}"  # custom variable for your app logic
      SCYLLA_CQL_PORT: "${SCYLLA_CQL_PORT:-9042}"
      SCYLLA_REST_PORT: "${SCYLLA_REST_PORT:-9180}"
    env_file:
      - ./.env
    ports:
      - "${SCYLLA_CQL_PORT}:9042"   # Forward from env to container port 9042
      - "${SCYLLA_REST_PORT}:9180"  # Forward from env to container port 9180 (optional)
    volumes:
      - scylla_data:/var/lib/scylla
    networks:
      - app-network

volumes:
  pg_data:
  minio_data:
  scylla_data:

networks:
  app-network:
    driver: bridge