
x-env: &horizon-environment-variables
  env_file:
    - ./.env
  environment:
    APP_PORT: "${APP_PORT}"
    APP_METRICS_PORT: "${APP_METRICS_PORT}"
    APP_NAME: "${APP_NAME}"
    APP_ENV: "${APP_ENV}"
    APP_CLIENT_URL: "${APP_CLIENT_URL}"
    APP_TOKEN: "${APP_TOKEN}"
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    POSTGRES_DB: "${POSTGRES_DB}"
    POSTGRES_HOST: "${POSTGRES_HOST}"
    POSTGRES_PORT: "${POSTGRES_PORT}"
    PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
    PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    PGADMIN_HOST: "${PGADMIN_HOST}"
    PGADMIN_PORT: "${PGADMIN_PORT}"
    SCYLLA_CLUSTER_NAME: "${SCYLLA_CLUSTER_NAME}"
    SCYLLA_KEYSPACE: "${SCYLLA_KEYSPACE}"
    SCYLLA_CQL_PORT: "${SCYLLA_CQL_PORT}"
    SCYLLA_REST_PORT: "${SCYLLA_REST_PORT}"
    REDIS_PORT: "${REDIS_PORT}"
    REDIS_HOST: "${REDIS_HOST}"
    REDIS_PASSWORD: "${REDIS_PASSWORD}"
    REDIS_USERNAME: "${REDIS_USERNAME}"
    REDISINSIGHT_HOST: "${REDISINSIGHT_HOST}"
    REDISINSIGHT_PORT: "${REDISINSIGHT_PORT}"
    SMTP_HOST: "${SMTP_HOST}"
    SMTP_PORT: "${SMTP_PORT}"
    SMTP_USERNAME: "${SMTP_USERNAME}"
    SMTP_PASSWORD: "${SMTP_PASSWORD}"
    SMTP_FROM: "${SMTP_FROM}"
    MAILPIT_UI_HOST: "${MAILPIT_UI_HOST}"
    MAILPIT_UI_PORT: "${MAILPIT_UI_PORT}"
    STORAGE_DRIVER: "${STORAGE_DRIVER}"
    STORAGE_ACCESS_KEY: "${STORAGE_ACCESS_KEY}"
    STORAGE_SECRET_KEY: "${STORAGE_SECRET_KEY}"
    STORAGE_HOST: "${STORAGE_HOST}"
    STORAGE_REGION: "${STORAGE_REGION}"
    STORAGE_BUCKET: "${STORAGE_BUCKET}"
    STORAGE_API_PORT: "${STORAGE_API_PORT}"
    STORAGE_CONSOLE_PORT: "${STORAGE_CONSOLE_PORT}"
    NATS_HOST: "${NATS_HOST}"
    NATS_CLIENT_PORT: "${NATS_CLIENT_PORT}"
    NATS_MONITOR_PORT: "${NATS_MONITOR_PORT}"
    NATS_WEBSOCKET_PORT: "${NATS_WEBSOCKET_PORT}"
    PASSWORD_MEMORY: "${PASSWORD_MEMORY}"
    PASSWORD_ITERATIONS: "${PASSWORD_ITERATIONS}"
    PASSWORD_PARALLELISM: "${PASSWORD_PARALLELISM}"
    PASSWORD_SALT_LENTH: "${PASSWORD_SALT_LENTH}"
    PASSWORD_KEY_LENGTH: "${PASSWORD_KEY_LENGTH}"
    TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
    TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
    TWILIO_SENDER: "${TWILIO_SENDER}"
    TWILIO_TEST_RECIEVER: "${TWILIO_TEST_RECIEVER}"


services:
  app:
    build: .
    image: hot-reloading-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_METRICS_PORT}:${APP_METRICS_PORT}"
    volumes:
      - ./:/app

    <<: *horizon-environment-variables
    depends_on:
      - postgres
      - redis
      - nats
      - minio
      - pgadmin
      - redisinsight
      - mailpit
      - scylla
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":${STORAGE_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: "${STORAGE_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${STORAGE_SECRET_KEY}"
    env_file:
      - ./.env
    ports:
      - "${STORAGE_API_PORT}:9000"
      - "${STORAGE_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    env_file:
      - ./.env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - app-network
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    env_file:
      - ./.env
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-network
    
  redisinsight:  
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    environment: 
      REDISINSIGHT_PORT: "${REDISINSIGHT_PORT}"
    env_file:
      - ./.env
    ports:
      - "${REDISINSIGHT_PORT}:${REDISINSIGHT_PORT}"
    depends_on:
      - redis
    networks:
      - app-network
  
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    environment:
      MAILPIT_SMTP_PORT: "${MAILPIT_SMTP_PORT}"
      MAILPIT_UI_PORT: "${MAILPIT_UI_PORT}"
    env_file:
      - ./.env
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_UI_PORT:-8025}:8025"
    networks:
      - app-network
  
  nats:
    image: nats:latest
    container_name: nats
    restart: always
    environment:
      NATS_MONITOR_PORT: "${NATS_MONITOR_PORT}"
      NATS_CLIENT_PORT: "${NATS_CLIENT_PORT}"
      NATS_WEBSOCKET_PORT: "${NATS_WEBSOCKET_PORT}"
    env_file:
      - ./.env
    ports:
      - "${NATS_CLIENT_PORT}:${NATS_CLIENT_PORT}"
      - "${NATS_MONITOR_PORT}:${NATS_MONITOR_PORT}"
      - "${NATS_WEBSOCKET_PORT}:${NATS_WEBSOCKET_PORT}"
    volumes:
      - ./config/nats.conf:/container/nats.conf
    command: "-c /container/nats.conf"
    networks:
      - app-network
  
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    restart: always
    environment:
      SCYLLA_CLUSTER_NAME: "${SCYLLA_CLUSTER_NAME:-scylla-cluster}"
      SCYLLA_KEYSPACE: "${SCYLLA_KEYSPACE:-mykeyspace}"  # custom variable for your app logic
      SCYLLA_CQL_PORT: "${SCYLLA_CQL_PORT:-9042}"
      SCYLLA_REST_PORT: "${SCYLLA_REST_PORT:-9180}"
    env_file:
      - ./.env
    ports:
      - "${SCYLLA_CQL_PORT}:9042"   # Forward from env to container port 9042
      - "${SCYLLA_REST_PORT}:9180"  # Forward from env to container port 9180 (optional)
    volumes:
      - scylla_data:/var/lib/scylla
    networks:
      - app-network

volumes:
  pg_data:
  minio_data:
  scylla_data:

networks:
  app-network:
    driver: bridge